### ISSUE TITLE
Authentication with Scuttle isn't working

### ISSUE THREAD

**Issue by Mebus** [shadybrooksoftware/Scuttle-For-Android#2]
Hallo,

the authentication with my scuttle installation isn't working.

What can I do to debug this?

Thanks

Mebus

**Comment by lucasvieites** [comment]
Hi,
I am having the same issue; when logging in I get "Username and/or password is incorrect".

I am downloading the code to have a look and see if I can fix it.

Cheers,
Lucas

**Comment by lucasvieites** [comment]
Hi,
I fixed this for me by incrementing the "c.setConnectTimeout(5000)" in com/shadybrooksoftware/scuttle/ScuttleBookmarkList.java
Cheers,
Lucas
